### ISSUE TITLE
Error with Python2: unqualified exec is not allowed in function ...

### ISSUE THREAD

**Issue by ThWulf** [matze-dd/YaLafi#38]
When using `yalafi-grammarous` I had to change `python` to `python3` as `python` is Python 2 on my system. Leading to the error message:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/huecking/.config/nvim/plugged/YaLafi/yalafi/shell/__main__.py", line 3, in <module>
    from . import shell
  File "yalafi/shell/shell.py", line 124, in <module>
    from yalafi import tex2txt
  File "yalafi/tex2txt.py", line 29, in <module>
    from . import parameters, parser, utils
  File "yalafi/parameters.py", line 23, in <module>
    from .defs import Environ, EquEnv, Macro
  File "yalafi/defs.py", line 19, in <module>
    from . import utils
  File "yalafi/utils.py", line 119
    exec('import ' + mod)
SyntaxError: unqualified exec is not allowed in function 'get_module_handler' because it contains a nested function with free variables
```
Maybe this could be change in the code? Otherwise this issue may just help people to know what they have to change. Maybe it could be mentioned in the docs that it works only with python3

**Comment by matze-dd** [comment]
Thank you for this observation. I was always thinking whether one should add Python version tests into the scripts. But as Python version 2 now is deprecated, the hope is that operating systems will migrate to version 3.

I have added requirement of version 3 in the README intro, but will leave this issue open so that others can find it quickly.

**Comment by Konfekt** [comment]
Fine with deprecating Python 2, but  latest Opensuse 15.3 uses Python 2 by default, and installing the Yalafi module for Python 3 makes the `ltyc.vim` compiler unusable due to

```vim
" .vim/compiler/ltyc.vim (lines 65-69)
call system('python -c "import yalafi"')
if v:shell_error != 0
    echoerr s:pref . 'install the Python module YaLafi.'
    finish
endif
```

**Comment by Konfekt** [comment]
If python3 is needed, then the check should use `python3` instead of `python` (=`python2` on latest Opensuse).

**Comment by Konfekt** [comment]
Similar with the invocations

```vim
" .vim/compiler/ltyc.vim (lines 83-84)
let &l:makeprg =
        \ 'python3 -m yalafi.shell'
" .vim/compiler/ltyc.vim (lines 61-64)
if !executable('python3')
    echoerr s:pref . 'install Python.'
    finish
endif
```
