### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lin' on tex-file

### ISSUE THREAD

**Issue by petRUShka** [matze-dd/YaLafi#73]
I run vlty via VIM plus vimtex on tex-file with quite complex template. As a result I get error: 
```
AttributeError: 'NoneType' object has no attribute 'lin'
```

Run command

```bash
python3 -m yalafi.shell --lt-command languagetool --language ru \
        --disable "WHITESPACE_RULE" --enable "" \
        --disablecategories "" --enablecategories "" \
        --documentclass "" \
        --packages "amsbsy,keyval,fontenc,enumerate,eufrak,calc,inputenc,url,amsopn,babel,bm,amssymb,epstopdf-base,trig,amsmath,revsymb,amsthm,array,longtab le,caption2,natbib,amstext,mathtext,graphics,amsgen,graphicx,ifthen,caption3,extsizes,amsfonts" \
        --encoding cp866 \
        my_article.tex
```

Output:

```
=== my_article.tex
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.amsbsy'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.keyval'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.fontenc'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.enumerate'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.eufrak'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.calc'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.inputenc'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.url'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.amsopn'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.babel'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.bm'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.amssymb'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.epstopdf_base'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.trig'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.revsymb'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.array'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.longtab_le'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.caption2'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.natbib'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.amstext'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.mathtext'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.graphics'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.amsgen'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.ifthen'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.caption3'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.extsizes'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.amsfonts'
*** yalafi.shell: warning:
*** could not load module 'yalafi.documentclasses.revtex4'
*** yalafi.shell: warning:
*** could not load module 'yalafi.packages.enumerate'
Expected text language: Russian
Working on STDIN...
=== my_article.tex ===
1.) Line 18, column 20, Rule ID: UPPERCASE_SENTENCE_START
Message: Это предложение не начинается с заглавной буквы
Suggestion: Maik
 maik   Гипотеза Лемма    russian  О конечности чи...
 ^^^^

=== my_article.tex ===
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/yalafi/shell/__main__.py", line 3, in <module>
    from . import shell
  File "/usr/lib/python3.8/site-packages/yalafi/shell/shell.py", line 351, in <module>
    gentext.generate_text_report(proofreader.run_proofreader, sys.stdout)
  File "/usr/lib/python3.8/site-packages/yalafi/shell/gentext.py", line 93, in generate_text_report
    output_text_report(tex, plain, charmap, matches, file, out)
  File "/usr/lib/python3.8/site-packages/yalafi/shell/gentext.py", line 48, in output_text_report
    s = (str(nr) + '.) Line ' + str(lc.lin) + ', column ' + str(lc.col)
AttributeError: 'NoneType' object has no attribute 'lin'
```

**Comment by matze-dd** [comment]
Thank you for reporting this!

From looking at the trace, I cannot make an informed guess where to look first for the bug. Could you please try to build a minimal LaTeX example that triggers the problem? Thanks in advance.

**Comment by matze-dd** [comment]
@petRUShka, if you cannot find the critical part in your large document, here are two ideas that came to my mind.

Vlty forwards the error messages to vimtex in a text format. For historical reasons, the generation of this messages uses a different code for mapping of character positions than during generation of an HTML report, say xxx.html. So, you could try
```
python3 -m yalafi.shell --lt-command languagetool --encoding cp866 --language ru-RU --output html my_article.tex > xxx.html
```
and open file xxx.html in a Web browser. Does this work? Looking at your error trace from the initial post, it should be the second problem.

If this doesn't help, I have made a little change to the code generating the messages for vimtex. It should not simply crash, but before print an error message withe line and column in the plain text that has been sent to LanguageTool. You can install the new yalafi version with:
```
sudo python3 -m pip install git+https://github.com/matze-dd/YaLafi.git@master
```

Now,
```
python3 -m yalafi.shell --lt-command languagetool --encoding cp866 --language ru-RU my_article.tex
```
should print the new message with line and column number. You can create the plain text, say xxx.txt, with
```
python3 -m yalafi --ienc cp866 --lang ru-RU my_article.tex > xxx.txt
```

**Comment by matze-dd** [comment]
Sorry for the noise, only want to propose another version that might fix the issue. (The bug you encountered really worries me, as it might relate to the core functionality of yalafi.)

If you install the version from branch Issue-77 by
```
sudo python3 -m pip install git+https://github.com/matze-dd/YaLafi.git@Issue-77
```
this might solve the problem in the best case. Otherwise, could you please have a look at the previous post?

Sorry again for the noise.

**Comment by petRUShka** [comment]
@matze-dd, sorry I wasn't able to check on this. issue-77 branch is working fine on my file without any errors. Should I check something else?

**Comment by matze-dd** [comment]
> @matze-dd, sorry I wasn't able to check on this.

@petRUShka, no reason to say sorry! After all it's weekend. It's me who made the noise.

Thank you for testing! I have merged branch Issue-77 to master.
